version: 2
updates:
- package-ecosystem: "sbt"
  directory: "/"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 7
  ignore:
  - dependency-name: "org.apache.spark:*"
  - dependency-name: "org.scala-lang:*"
