rules = [
  RemoveUnused,
  OrganizeImports,
  RedundantSyntax,

  // Rules from https://github.com/xuwei-k/scalafix-rules
  DirectoryAndPackageName
  FileNameConsistent
  IncorrectScaladocParam

  // Our rules from this repo
  Disallowed
  FinalCaseClass
  NamedLiteralArguments
  TypeSafetyComment
  OptionWhen
  ExplicitTypeArgs
]

OrganizeImports.targetDialect = Scala3

OrganizeImports.groups = [
  "java."
  "scala."
  "*"
  "com.choreograph."
]

Disallowed.methods = [
  {
    "symbol": "scala.Predef.println",
    "message": "Instead of println please use a slf4j logger"
  },
  {
    "symbol": "scala.Option.get"
    "message": "Option.get in unsafe and should be avoided. Please capture in the type system that the type is really Some or use getOrElse and throw and exception with a clear message if None"
  },
  {
    "symbol": "scala.reflect.Selectable.reflectiveSelectable",
    "message": "Reflective calls are slow. Please consider if you can use a different approach like type classes. Perhaps existing type classes like Projector, Selector could be used?"
  },
  {
    "symbol": "com.google.common.io.Resources.getResource",
    "message": "Instead of getResource please use com.choreograph.superspine.connectors.GetResource"
  },
  {
    "symbol": "com.choreograph.tyda.sql.ast.SqlExpr.LiteralNull"
    "message": "Untyped nulls commonly leads to bugs, use com.choreograph.tyda.sql.typedNull helper instead"
  }
]

ExplicitTypeArgs.methods = [
  "com/choreograph/tyda/ExprApi#select()."
]

lint.error = [
  "DirectoryAndPackageName",
  "Disallowed"
  "FileNameConsistent"
  "FinalCaseClass"
  "IncorrectScaladocParam"
  "TypeSafetyComment"
  "OptionWhen"
  "ExplicitTypeArgs"
]
