version = 3.11.3
runner.dialect = scala3

comments.wrap = standalone
comments.wrapStandaloneSlcAsSlc = true
comments.wrapSingleLineMlcAsSlc = true
docstrings.wrapMaxColumn = 80
maxColumn = 110

# Reduce the size of diffs
align.preset=none

# Do not depend on existing newlines for formatting
newlines.source=fold
newlines.selectChains=unfold
newlines.forceBeforeMultilineAssign=def

rewrite.rules = [RedundantBraces, RemoveSemicolons]

rewrite.scala3.convertToNewSyntax=true
rewrite.scala3.newSyntax.control=false
rewrite.scala3.newSyntax.deprecated=true

fileOverride {
  "glob:**/src/test/**.scala" {
    rewrite.rules = []
  }
}

# Do not reformat comments in scalafix tests as it messes up the test configuration
fileOverride {
  "glob:**/scalafix/*put/**.scala" {
     comments.wrap = "no"
  }
}
