package com.choreograph.tyda.json

import scala.jdk.CollectionConverters.*
import scala.util.Random

import com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec
import com.github.plokhotnyuk.jsoniter_scala.core.writeToString
import com.networknt.schema.InputFormat
import com.networknt.schema.SchemaRegistry
import com.networknt.schema.SpecificationVersion
import org.scalatest.funsuite.AnyFunSuite

import com.choreograph.tyda.Arbitrary
import com.choreograph.tyda.Codec
import com.choreograph.tyda.Codec.EnumAsString
import com.choreograph.tyda.Date
import com.choreograph.tyda.Decimal
import com.choreograph.tyda.Duration
import com.choreograph.tyda.Timestamp
import com.choreograph.tyda.TypeName

object CodecToJsonSchemaConformanceSpec {
  final case class SimpleProduct(a: Int, b: Option[String]) derives Arbitrary, Codec
  final case class AllOptionalProduct(a: Option[Int], b: Option[String]) derives Arbitrary, Codec

  enum Color derives EnumAsString, Arbitrary {
    case Red, Green, Blue
  }

  enum Animal derives Codec, Arbitrary {
    case Dog(name: String)
    case Cat
  }

  enum NastyTypes derives Codec, Arbitrary {
    case NestedOptions(a: Option[Option[Option[Int]]])
    case MapOfMaps(m: Map[String, Map[String, Int]])
  }

  sealed trait SealedTrait derives Codec, Arbitrary
  object SealedTrait {
    final case class A(a: Int) extends SealedTrait
    final case class B(b: String) extends SealedTrait
    case object C extends SealedTrait
  }

  final case class NestedSum(a: Int, b: SealedTrait) derives Codec, Arbitrary
}

class CodecToJsonSchemaConformanceSpec extends AnyFunSuite {
  import CodecToJsonSchemaConformanceSpec.*

  private val schemaRegistry = SchemaRegistry.withDefaultDialect(SpecificationVersion.DRAFT_2020_12)

  /** Tests that the JSON Schema generated by CodecToJsonSchema validates the
    * JSON produced by CodecToJsoniter for the same type.
    */
  def jsonMatchesSchemaFor[T: Arbitrary: Codec: TypeName] =
    test(s"schema validates ${TypeName.name[T]}") {
      given JsonValueCodec[T] = CodecToJsoniter.create[T]
      val schemaStr = CodecToJsonSchema.create[T]
      val schema = schemaRegistry.getSchema(schemaStr, InputFormat.JSON)

      def validate[T: JsonValueCodec](json: T) =
        schema.validate(writeToString(json), InputFormat.JSON).asScala

      for (_ <- 0 until 100) {
        val shrinkable = Arbitrary[T].shrinkable(Random)
        if !validate(shrinkable.value).isEmpty then {
          val minimized = shrinkable.minimize(input => !validate(input).isEmpty)
          fail(s"""Schema validation failed for ${TypeName.name[T]}
               |Minimized input: $minimized
               |JSON: ${writeToString(minimized)}
               |Schema: $schemaStr
               |Errors:
               |  ${validate(minimized).mkString("\n  ")}""".stripMargin)
        }
      }
    }

  jsonMatchesSchemaFor[Boolean]
  jsonMatchesSchemaFor[Byte]
  jsonMatchesSchemaFor[Short]
  jsonMatchesSchemaFor[Int]
  jsonMatchesSchemaFor[Long]
  jsonMatchesSchemaFor[Float]
  jsonMatchesSchemaFor[Double]
  jsonMatchesSchemaFor[Decimal[3, 0]]
  jsonMatchesSchemaFor[Decimal[15, 5]]
  jsonMatchesSchemaFor[Decimal[38, 9]]
  jsonMatchesSchemaFor[Timestamp]
  jsonMatchesSchemaFor[Date]
  jsonMatchesSchemaFor[Duration]
  jsonMatchesSchemaFor[String]
  jsonMatchesSchemaFor[Option[Int]]
  jsonMatchesSchemaFor[Option[Option[Int]]]
  jsonMatchesSchemaFor[Seq[Int]]
  jsonMatchesSchemaFor[Seq[SimpleProduct]]
  jsonMatchesSchemaFor[Map[String, Int]]
  jsonMatchesSchemaFor[Map[SimpleProduct, SimpleProduct]]
  jsonMatchesSchemaFor[EmptyTuple]
  jsonMatchesSchemaFor[AllOptionalProduct]
  jsonMatchesSchemaFor[SimpleProduct]
  jsonMatchesSchemaFor[Color]
  jsonMatchesSchemaFor[Animal]
  jsonMatchesSchemaFor[NastyTypes]
  jsonMatchesSchemaFor[SealedTrait]
  jsonMatchesSchemaFor[NestedSum]
}
