package com.choreograph.tyda

import scala.annotation.implicitNotFound
import scala.compiletime.erasedValue
import scala.compiletime.summonFrom
import scala.compiletime.summonInline
import scala.deriving.Mirror

/** Type class that service as evidence that a type can be used in grouping
  * operations.
  *
  * This is all types except for Map and types that contain Map.
  */
@implicitNotFound(
  "Type ${T} is not groupable.\n" + "If ${T} is a type parameter add a context bound: [${T}: Groupable]\n" +
    "If ${T} is an opaque type the add a given Groupable[${T}] = Groupable.derived to the companion object\n"
)
trait Groupable[T] extends Serializable

object Groupable {
  def apply[T: Groupable as g]: Groupable[T] = g

  private case object Singleton extends Groupable[Any]

  inline given derived[T]: Groupable[T] = {
    check[T]

    // TYPE SAFETY: Groupable has no functionallity and is just used as evidence
    Singleton.asInstanceOf[Groupable[T]]
  }

  private inline def check[T]: Unit =
    inline erasedValue[T] match {
      case _: (EmptyTuple | Boolean | Byte | Short | Int | Long | Float | Double | String) => ()
      case _: Option[t] => check[t]
      case _: Seq[t] => check[t]
      case _: (h *: t) =>
        check[h]
        check[t]
      // TODO: It seems like even if this mirrors are only used at compile time
      // they are still present in the the generated bytecode. We should look into reporting
      // that as a bug to scala to avoid the bytecode bloat.
      case _ => summonFrom {
          case m: Mirror.ProductOf[T] => check[m.MirroredElemTypes]
          case m: Mirror.SumOf[T] => check[m.MirroredElemTypes]
          case _ => summonInline[Groupable[T]]: Unit
        }
    }
}
